In [2]:
from numpy.core.arrayprint import printoptions
from numpy.lib.function_base import extract
import scipy.io
import numpy as np
import pandas as pd
import os
import json

In [10]:
def extract_list(x):
    if(type(x[0]) == list and len(x[0]) == 1):
        return extract_list(x[0])
    return x[0]

In [23]:
x = scipy.io.loadmat('eeg_200605191428_epochs.mat')
x

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Oct 11 14:30:55 2006',
 '__version__': '1.0',
 '__globals__': [],
 'target': array([[2]], dtype=uint8),
 'stimuli': array([[1, 3, 4, 5, 2, 6, 2, 3, 6, 1, 5, 4, 5, 2, 6, 3, 4, 1, 6, 2, 5, 1,
         4, 3, 5, 2, 4, 1, 6, 3, 5, 2, 1, 3, 6, 4, 6, 1, 5, 3, 4, 2, 6, 1,
         2, 4, 5, 3, 2, 6, 5, 1, 4, 3, 6, 3, 5, 4, 2, 1, 1, 5, 2, 3, 4, 6,
         2, 5, 4, 1, 6, 3, 6, 4, 1, 2, 5, 3, 6, 3, 2, 5, 4, 1, 1, 3, 6, 4,
         5, 2, 2, 5, 1, 6, 4, 3, 3, 1, 2, 6, 4, 5, 2, 3, 6, 1, 5, 4, 5, 3,
         6, 1, 4, 2, 3, 1, 4, 2, 5, 6, 4, 6, 2, 3, 5, 1, 5, 3, 6, 2, 4, 1,
         6, 3, 5, 2, 4, 1]], dtype=uint8),
 'targets_counted': array([[23]], dtype=uint8),
 'data': array([[  -776.0625 ,   -775.28125,   -778.28125, ...,      0.     ,
              0.     ,      0.     ],
        [ 22804.0625 ,  22805.125  ,  22802.21875, ...,      0.     ,
              0.     ,      0.     ],
        [-13855.03125, -13855.28125, -13858.96875

In [24]:
df = pd.DataFrame(x['data'])
df = df.set_index(0)
del x['data']

In [25]:
x

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Oct 11 14:30:55 2006',
 '__version__': '1.0',
 '__globals__': [],
 'target': array([[2]], dtype=uint8),
 'stimuli': array([[1, 3, 4, 5, 2, 6, 2, 3, 6, 1, 5, 4, 5, 2, 6, 3, 4, 1, 6, 2, 5, 1,
         4, 3, 5, 2, 4, 1, 6, 3, 5, 2, 1, 3, 6, 4, 6, 1, 5, 3, 4, 2, 6, 1,
         2, 4, 5, 3, 2, 6, 5, 1, 4, 3, 6, 3, 5, 4, 2, 1, 1, 5, 2, 3, 4, 6,
         2, 5, 4, 1, 6, 3, 6, 4, 1, 2, 5, 3, 6, 3, 2, 5, 4, 1, 1, 3, 6, 4,
         5, 2, 2, 5, 1, 6, 4, 3, 3, 1, 2, 6, 4, 5, 2, 3, 6, 1, 5, 4, 5, 3,
         6, 1, 4, 2, 3, 1, 4, 2, 5, 6, 4, 6, 2, 3, 5, 1, 5, 3, 6, 2, 4, 1,
         6, 3, 5, 2, 4, 1]], dtype=uint8),
 'targets_counted': array([[23]], dtype=uint8),
 'events': array([[2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.5744e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6144e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6

In [26]:
keys = list(x.keys())
for i in keys:
    if "__" in i:
        del x[i]
x

{'target': array([[2]], dtype=uint8),
 'stimuli': array([[1, 3, 4, 5, 2, 6, 2, 3, 6, 1, 5, 4, 5, 2, 6, 3, 4, 1, 6, 2, 5, 1,
         4, 3, 5, 2, 4, 1, 6, 3, 5, 2, 1, 3, 6, 4, 6, 1, 5, 3, 4, 2, 6, 1,
         2, 4, 5, 3, 2, 6, 5, 1, 4, 3, 6, 3, 5, 4, 2, 1, 1, 5, 2, 3, 4, 6,
         2, 5, 4, 1, 6, 3, 6, 4, 1, 2, 5, 3, 6, 3, 2, 5, 4, 1, 1, 3, 6, 4,
         5, 2, 2, 5, 1, 6, 4, 3, 3, 1, 2, 6, 4, 5, 2, 3, 6, 1, 5, 4, 5, 3,
         6, 1, 4, 2, 3, 1, 4, 2, 5, 6, 4, 6, 2, 3, 5, 1, 5, 3, 6, 2, 4, 1,
         6, 3, 5, 2, 4, 1]], dtype=uint8),
 'targets_counted': array([[23]], dtype=uint8),
 'events': array([[2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.5744e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6144e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6545e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6946e+01],
        [2.0060e+03, 5.0000e+00, 1.9

In [27]:
type(x['events']) == np.ndarray

True

In [35]:
list(x.values())

[array([[2]], dtype=uint8),
 array([[1, 3, 4, 5, 2, 6, 2, 3, 6, 1, 5, 4, 5, 2, 6, 3, 4, 1, 6, 2, 5, 1,
         4, 3, 5, 2, 4, 1, 6, 3, 5, 2, 1, 3, 6, 4, 6, 1, 5, 3, 4, 2, 6, 1,
         2, 4, 5, 3, 2, 6, 5, 1, 4, 3, 6, 3, 5, 4, 2, 1, 1, 5, 2, 3, 4, 6,
         2, 5, 4, 1, 6, 3, 6, 4, 1, 2, 5, 3, 6, 3, 2, 5, 4, 1, 1, 3, 6, 4,
         5, 2, 2, 5, 1, 6, 4, 3, 3, 1, 2, 6, 4, 5, 2, 3, 6, 1, 5, 4, 5, 3,
         6, 1, 4, 2, 3, 1, 4, 2, 5, 6, 4, 6, 2, 3, 5, 1, 5, 3, 6, 2, 4, 1,
         6, 3, 5, 2, 4, 1]], dtype=uint8),
 array([[23]], dtype=uint8),
 array([[2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.5744e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6144e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6545e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.6946e+01],
        [2.0060e+03, 5.0000e+00, 1.9000e+01, 1.4000e+01, 2.7000e+01,
         1.7346e+

In [43]:
temp = {}
for i,j in x.items():
    temp[i] = list(extract_list(j))
x = temp

{'target': [2],
 'stimuli': [1,
  3,
  4,
  5,
  2,
  6,
  2,
  3,
  6,
  1,
  5,
  4,
  5,
  2,
  6,
  3,
  4,
  1,
  6,
  2,
  5,
  1,
  4,
  3,
  5,
  2,
  4,
  1,
  6,
  3,
  5,
  2,
  1,
  3,
  6,
  4,
  6,
  1,
  5,
  3,
  4,
  2,
  6,
  1,
  2,
  4,
  5,
  3,
  2,
  6,
  5,
  1,
  4,
  3,
  6,
  3,
  5,
  4,
  2,
  1,
  1,
  5,
  2,
  3,
  4,
  6,
  2,
  5,
  4,
  1,
  6,
  3,
  6,
  4,
  1,
  2,
  5,
  3,
  6,
  3,
  2,
  5,
  4,
  1,
  1,
  3,
  6,
  4,
  5,
  2,
  2,
  5,
  1,
  6,
  4,
  3,
  3,
  1,
  2,
  6,
  4,
  5,
  2,
  3,
  6,
  1,
  5,
  4,
  5,
  3,
  6,
  1,
  4,
  2,
  3,
  1,
  4,
  2,
  5,
  6,
  4,
  6,
  2,
  3,
  5,
  1,
  5,
  3,
  6,
  2,
  4,
  1,
  6,
  3,
  5,
  2,
  4,
  1],
 'targets_counted': [23],
 'events': [2006.0, 5.0, 19.0, 14.0, 27.0, 15.744]}

In [41]:
x['target']

array([[2]], dtype=uint8)